Update paths to be universal
GedasFX/decky-cloud-save pull request #57
Opened 2024-01-27 21:40 UTC by mdeguzis

Other alternative OS's, namely ChimeraOS can and do use Deck Loader. Update the paths to reflect the user home directory.

2024-04-30 14:13 UTC, GedasFX requested changes

2024-04-30 14:14 UTC, GedasFX commented on README.md
> +~/homebrew/plugins/decky-cloud-save/rclone bisync --filter-from ~/homebrew/settings/decky-cloud-save/sync_paths_filter.txt / backend:decky-cloud-save --copy-links --resync
I'm sorry I didn't know how github reviews worked... I left a comment when you made the PR here and didnt realize it was pending. Thought I got ghosted 😅

2024-04-30 14:25 UTC, mdeguzis commented on README.md
> +~/homebrew/plugins/decky-cloud-save/rclone bisync --filter-from ~/homebrew/settings/decky-cloud-save/sync_paths_filter.txt / backend:decky-cloud-save --copy-links --resync
This isn't a relative path change. This just ensures a dynamic home is used before the rest of the path.

2024-04-30 14:30 UTC, GedasFX commented on README.md
> +~/homebrew/plugins/decky-cloud-save/rclone bisync --filter-from ~/homebrew/settings/decky-cloud-save/sync_paths_filter.txt / backend:decky-cloud-save --copy-links --resync
Yeah, looking into this now, this looks alright

2024-04-30 14:30 UTC, GedasFX approved these changes

2024-04-30 14:30 UTC, merged

2024-04-30 18:40 UTC, Emiliopg91 commented
@GedasFX why not using decky_plugin.pyi consts?

2024-05-01 07:39 UTC, GedasFX commented
@Emiliopg91 this is in readme.